config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get '/calc', to: 'pages#calc'
  get '/history', to: 'pages#history'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def history
    session[:previous_results] ||= []

    if params.key?(:numbers)
      @result = params[:numbers].values.map(&:to_f).sum
      session[:previous_results] << @result
    else
      @result = 'ninguno de momento'
    end

    @previous_results = session[:previous_results]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SanzClimaPrueba</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/calc.html.erb
<div class="container mt-5">

<h1>Cálculo</h1>
<p>Desde aquí introduce los números que quieres sumar:</p>

<%= simple_form_for :numbers, url: history_path, method: :get do |f| %>
  <%= f.input :number1, label: 'Número:', hint: "Para decimales use un punto (.) en vez de una coma (,)" %>
  <%= f.input :number2, label: 'Número:' %>

  <div data-controller="calculator" id="input">
    <button class="btn btn-success" type="button" data-action="click->calculator#addInput">+</button>
  </div>

  <br>
  <%= f.button :submit, 'Suma!', class: "btn btn-primary" %>
<% end %>

<br>
<%= link_to "Página de inicio", root_path, class: "btn btn-danger" %>


</div>

app/views/pages/history.html.erb
<div class="container mt-5">

<h1>Suma</h1>

<% if @result.present? %>
  <p> El resultado es <%= @result %>.</p>
<% end %>

<% if @previous_results %>
<h3>Mis resultados anteriores:</h3>
<% @previous_results.each do |result| %>
  <p> El resultado ha sido <%= result %>.</p>
<% end %>
<% end %>

<%= link_to "Calcular", calc_path, class: "btn btn-primary" %>

<%= link_to "Página de incio", root_path, class: "btn btn-danger" %>

</div>

app/views/pages/home.html.erb
<div class="container mt-5">

<h1>Prueba Sanz Clima</h1>
<p>Muy buenas! Esta es la páina de inicio, desde aquí viaja para hacer la suma de los números o mirar tus cálculos anteriores.</p>
<p>Un saludo muy cordial,</p>
<a href="https://gabrielmr.com" target="_blank">Gabriel</a>.
<br>
<br>

<%= link_to "Calcula", calc_path, class: "btn btn-primary" %>
<%= link_to "Mira tus cálculos anteriores", history_path, class: "btn btn-primary" %>

</div>